services:
  bot:
    build: .
    container_name: symelix_bot
    environment:
      - TZ=Europe/Kyiv
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - .:/app
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - db
      - redis

  celery:
    build: .
    container_name: symelix_celery
    environment:
      - TZ=Europe/Kyiv
    command: celery -A tasks.celery_app worker --loglevel=info --pool=prefork
    volumes:
      - .:/app
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - bot
      - redis
      - db
    env_file:
      - .env
    restart: unless-stopped

  beat:
    build: .
    container_name: symelix_beat
    environment:
      - TZ=Europe/Kyiv
    command: celery -A tasks.celery_app beat --loglevel=info
    volumes:
      - .:/app
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - redis
      - db
    env_file:
      - .env
    restart: unless-stopped

  redis:
    image: redis:alpine
    container_name: symelix_redis
    restart: unless-stopped

  db:
    image: postgres:14
    container_name: symelix_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    ports:
      - "5432:5432"

volumes:
  postgres_data:
