services:
  bot:
    build: .
    container_name: symelix_bot
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: postgres:14
    container_name: symelix_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    ports:
      - "5432:5432"

volumes:
  postgres_data:
