services:
  bot:
    build: .
    container_name: symelix_bot
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - .:/app
    depends_on:
      - db
      - redis

  db:
    image: postgres:14
    container_name: symelix_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    ports:
      - "5432:5432"

  redis:
    image: redis:alpine
    container_name: symelix_redis
    restart: unless-stopped

  celery:
    build: .
    container_name: symelix_celery
    command: celery -A worker.celery_app worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - bot
      - redis
      - db
    env_file:
      - .env
    restart: unless-stopped

  beat:
    build: .
    container_name: symelix_beat
    command: celery -A worker.celery_app beat --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis
      - db
    env_file:
      - .env
    restart: unless-stopped


volumes:
  postgres_data:
